# Site settings
title: DevJang development blog
url: "http://devjang.github.io"
baseurl: ""
#timezone: Asia/Seoul
description: >
  DevJang Development blog

# Your information
email: devjang2016@gmail.com
author: DevJang
# avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: Front-end Developer
#twitter_username: twitter_username
github_username: devJang

disqus_shortname: devjang

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

asset_url: /assets